import type { Metadata } from 'next';
import { Inter, DM_Sans } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import SessionWrapper from '@/app/components/SessionWrapper';
import Header from '@/app/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionWrapper>
			<html lang='en'>
				<body className={inter.className}>
					<Header/>
					{children}
				</body>
			</html>
		</SessionWrapper>
	);
}
